
-- ============================================
--HIGHEST SPENDING CUSTOMER PER COUNTRY--

WITH CUSTOMER_COUNTRY_SPENDING AS (
    SELECT 
        CUSTOMER.COUNTRY,
        CUSTOMER.FIRSTNAME,
        CUSTOMER.LASTNAME,
        SUM(INVOICE.TOTAL) AS TOTALSPENT
    FROM CUSTOMER
    JOIN INVOICE ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID
    GROUP BY CUSTOMER.CUSTOMERID, CUSTOMER.COUNTRY, CUSTOMER.FIRSTNAME, CUSTOMER.LASTNAME
),
COUNTRY_MAX_SPENDING AS (
    SELECT COUNTRY, MAX(TOTALSPENT) AS MAXSPENT
    FROM CUSTOMER_COUNTRY_SPENDING
    GROUP BY COUNTRY
)

SELECT 
    CCS.COUNTRY,
    CCS.FIRSTNAME,
    CCS.LASTNAME,
    ROUND(CCS.TOTALSPENT, 2) AS TOTALSPENT
FROM CUSTOMER_COUNTRY_SPENDING CCS
JOIN COUNTRY_MAX_SPENDING CMS 
    ON CCS.COUNTRY = CMS.COUNTRY 
    AND CCS.TOTALSPENT = CMS.MAXSPENT
ORDER BY CCS.TOTALSPENT DESC;

-- ============================================

-- ============================================
--VERIFY: CUSTOMERS FROM UK WITH THEIR SPENDING-- 
SELECT 
    CUSTOMER.FIRSTNAME,
    CUSTOMER.LASTNAME,
    CUSTOMER.COUNTRY,
    SUM(INVOICE.TOTAL) AS TOTALSPENT
FROM CUSTOMER
JOIN INVOICE ON CUSTOMER.CUSTOMERID = INVOICE.CUSTOMERID
WHERE CUSTOMER.COUNTRY = 'UNITED KINGDOM'
GROUP BY CUSTOMER.CUSTOMERID
ORDER BY TOTALSPENT DESC;

-- ============================================
--GENRE REVENUE SHARE (% OF TOTAL)--

WITH GENRE_REVENUE AS (
    SELECT 
        GENRE.NAME AS GENRENAME,
        SUM(INVOICELINE.UNITPRICE * INVOICELINE.QUANTITY) AS REVENUE
    FROM INVOICELINE
    JOIN TRACK ON INVOICELINE.TRACKID = TRACK.TRACKID
    JOIN GENRE ON TRACK.GENREID = GENRE.GENREID
    GROUP BY GENRE.GENREID, GENRE.NAME
),
TOTAL_REV AS (
    SELECT SUM(REVENUE) AS TOTALREVENUE FROM GENRE_REVENUE
)

SELECT 
    GR.GENRENAME,
    ROUND(GR.REVENUE, 2) AS REVENUE,
    ROUND((GR.REVENUE / TR.TOTALREVENUE) * 100, 2) AS PERCENTSHARE
FROM GENRE_REVENUE GR
CROSS JOIN TOTAL_REV TR
ORDER BY GR.REVENUE DESC;

-- ============================================

-- ============================================
--YEARLY REVENUE TREND--
WITH YEARLY_REVENUE AS (
    SELECT 
        SUBSTR(INVOICEDATE, 1, 4) AS YEAR,
        SUM(TOTAL) AS REVENUE,
        COUNT(*) AS INVOICECOUNT
    FROM INVOICE
    GROUP BY YEAR
)

SELECT 
    YEAR,
    ROUND(REVENUE, 2) AS REVENUE,
    INVOICECOUNT,
    ROUND(REVENUE / INVOICECOUNT, 2) AS AVGINVOICEVALUE
FROM YEARLY_REVENUE
ORDER BY YEAR;

-- ============================================

-- ============================================
-- Q4: BEST-SELLING ALBUM EACH YEAR--
WITH ALBUM_YEARLY_SALES AS (
    SELECT 
        SUBSTR(INVOICE.INVOICEDATE, 1, 4) AS YEAR,
        ALBUM.TITLE AS ALBUMTITLE,
        ARTIST.NAME AS ARTISTNAME,
        SUM(INVOICELINE.QUANTITY) AS UNITSSOLD
    FROM INVOICELINE
    JOIN TRACK ON INVOICELINE.TRACKID = TRACK.TRACKID
    JOIN ALBUM ON TRACK.ALBUMID = ALBUM.ALBUMID
    JOIN ARTIST ON ALBUM.ARTISTID = ARTIST.ARTISTID
    JOIN INVOICE ON INVOICELINE.INVOICEID = INVOICE.INVOICEID
    GROUP BY YEAR, ALBUM.ALBUMID, ALBUM.TITLE, ARTIST.NAME
),
YEARLY_MAX AS (
    SELECT YEAR, MAX(UNITSSOLD) AS MAXSOLD
    FROM ALBUM_YEARLY_SALES
    GROUP BY YEAR
)

SELECT 
    AYS.YEAR,
    AYS.ALBUMTITLE,
    AYS.ARTISTNAME,
    AYS.UNITSSOLD
FROM ALBUM_YEARLY_SALES AYS
JOIN YEARLY_MAX YM 
    ON AYS.YEAR = YM.YEAR 
    AND AYS.UNITSSOLD = YM.MAXSOLD
ORDER BY AYS.YEAR;

-- ============================================

-- ============================================
--CUSTOMER SEGMENTATION BY SPENDING--
WITH customer_totals AS (
    SELECT 
        CustomerId,
        SUM(Total) AS LifetimeSpending,
        COUNT(*) AS InvoiceCount
    FROM Invoice
    GROUP BY CustomerId
)

SELECT 
    Customer.FirstName,
    Customer.LastName,
    Customer.Country,
    ROUND(customer_totals.LifetimeSpending, 2) AS LifetimeSpending,
    customer_totals.InvoiceCount,
    CASE 
        WHEN customer_totals.LifetimeSpending >= 40 THEN 'Premium'
        WHEN customer_totals.LifetimeSpending >= 30 THEN 'Regular'
        ELSE 'Casual'
    END AS CustomerSegment
FROM Customer
JOIN customer_totals ON Customer.CustomerId = customer_totals.CustomerId
ORDER BY customer_totals.LifetimeSpending DESC;

-- ============================================
