--SHOW ALL CUSTOMERS--
SELECT * FROM Customer;

--SEE THE FIRST 5 CUSTOMERS--
SELECT * FROM Customer LIMIT 5;

--SEE THE FIRST 5 TRACKS--
SELECT * FROM Track LIMIT 5;

--SEE THE FIRST 5 INVOICES--
SELECT * FROM Invoice LIMIT 5;

--FIRST NAME, LAST NAME, EMAIL OF ALL CUSTOMERS--
SELECT FirstName, LastName, Email FROM Customer;

--ALL BRAZILIAN CUSTOMERS--
SELECT * FROM Customer
WHERE Country = 'Brazil';

--CUSTOMERS WHOSE FIRST NAME STARTS WITH A--
SELECT FirstName, LastName FROM Customer
WHERE FirstName  LIKE 'A%'

--TRACKS LONGER THAN 5 MINUTES--
SELECT Name, Milliseconds FROM Track
WHERE Milliseconds > 300000;

--ALL SALES SUPPORT AGENTS--
SELECT FirstName, LastName, Title FROM Employee
WHERE Title = 'Sales Support Agent';  

--ALL INVOICES FROM 2010--
SELECT * FROM Invoice
WHERE InvoiceDate LIKE '2010%';

--CUSTOMERS FROM USA, CANADA, 0R BRAZIL--
SELECT FirstName, LastName, Country FROM Customer
WHERE Country IN ('USA', 'Canada', 'Brazil')

--TRACKS WITH NO COMPOSER LISTED--
SELECT Name, Composer FROM Track
WHERE Composer IS NULL;

--CUSTOMERS NOT FROM USA--
SELECT FirstName, LastName, City FROM Customer
WHERE Country <> 'USA';

--CUSTOMERS SORTED A-Z BY LAST NAME--
SELECT FirstName, LastName FROM Customer
ORDER BY LastName ASC;

--CUSTOMERS SORTED Z-A BY LASTNAME--
SELECT FirstName, LastName FROM Customer
ORDER BY LastName DESC;

--SORT BY MULTIPLE COLUMNS:COUNTRY FIRST,THEN NAME WITHIN COUNTRY
SELECT FirstName, LastName, Country FROM Customer
ORDER BY Country  ASC, LastName  ASC;

--JUST SHOW ME 5 ROWS--
SELECT * FROM Track LIMIT 5;

--SHOW EACH UNIQUE COUNTRY ONLY ONCE--
SELECT DISTINCT COUNTRY FROM Customer
ORDER BY Country

--TOP 5 LONGEST TRACKS--
SELECT Name, Milliseconds FROM Track
ORDER BY Milliseconds DESC
LIMIT 5;

--TOP 5 SHORTEST TRACKS--
SELECT Name, Milliseconds FROM Track
ORDER BY Milliseconds ASC
LIMIT 5;

--10 LONGEST TRACKS--
SELECT Name, Milliseconds FROM Track
ORDER BY Milliseconds DESC
LIMIT 10;

--5 HIGHEST-VALUE INVOICES--
SELECT InvoiceId, CustomerId, Total FROM Invoice
ORDER BY Total DESC
LIMIT 5;

--ALL UNIQUE CUSTOMER COUNTRIES--
SELECT DISTINCT Country FROM Customer
ORDER BY Country ASC;

--3 MOST RECENTLY HIRED EMPLOYEES--
SELECT FirstName, LastName, Title, HireDate FROM Employee
ORDER BY Hiredate DESC
LIMIT 3;

--ALL UNIQUE GENRES ALPHABETIZED--
SELECT DISTINCT Name FROM Genre
ORDER BY Name ASC;

--5 LONGEST ROCK TRACKS--
SELECT Name, Milliseconds FROM Track
WHERE GenreId = 1
ORDER BY Milliseconds DESC
LIMIT 5;

--SHOW ALL ARTISTS IN ALPHABETICAL ORDER A-Z--
SELECT * FROM Artist
ORDER BY Name ASC



