-- ============================================
-- HackerRank SQL Solutions - Day 6 (COUNT, SUM, AVG, MIN, MAX, FLOOR)
-- ============================================

-- HACKERRANK #4: REVISING AGGREGATIONS - THE COUNT FUNCTION
-- COUNT THE NUMBER OF CITIES WITH POPULATION OVER 100,000
SELECT COUNT(*) FROM CITY WHERE POPULATION > 100000;


-- HACKERRANK #5: REVISING AGGREGATIONS - THE SUM FUNCTION
-- SUM THE POPULATIONS OF ALL CITIES IN CALIFORNIA DISTRICT
SELECT SUM(POPULATION) FROM CITY WHERE DISTRICT = 'CALIFORNIA';


-- HACKERRANK #6: REVISING AGGREGATIONS - AVERAGES
-- FIND THE AVERAGE POPULATION OF JAPANESE CITIES
SELECT AVG(POPULATION) FROM CITY WHERE COUNTRYCODE = 'JPN';


-- HACKERRANK #7: AVERAGE POPULATION
-- FIND THE AVERAGE POPULATION OF ALL CITIES, ROUNDED DOWN
-- NOTE: USED FLOOR() BECAUSE THE PROBLEM SAID "ROUNDED DOWN"
SELECT FLOOR(AVG(POPULATION)) FROM CITY;


-- HACKERRANK #8: JAPAN POPULATION
-- SUM POPULATIONS OF ALL JAPANESE CITIES (SAME AS #5 BUT DIFFERENT COUNTRY)
SELECT SUM(POPULATION) FROM CITY WHERE COUNTRYCODE = 'JPN';


-- HACKERRANK #10: POPULATION DENSITY DIFFERENCE
-- FIND THE DIFFERENCE BETWEEN THE LARGEST AND SMALLEST CITY POPULATIONS
-- KEY INSIGHT: MAX - MIN GIVES THE RANGE/SPREAD OF VALUES
SELECT MAX(POPULATION) - MIN(POPULATION) FROM CITY;


-- HACKERRANK #10: THE BLUNDER
-- SAMANTHA'S "0" KEYBOARD KEY WAS BROKEN. FIND THE DIFFERENCE BETWEEN
-- HER WRONG AVERAGE (ZEROS REMOVED) AND THE REAL AVERAGE. ROUND UP.
-- KEY INSIGHT: REPLACE(SALARY, '0', '') STRIPS ZEROS FROM EACH VALUE
-- KEY INSIGHT: CEIL() = ROUND UP. CEIL(2061.4) = 2062. CEIL(2061) = 2061.
SELECT 
    CEIL(AVG(SALARY) - AVG(REPLACE(SALARY, '0', '')))
FROM EMPLOYEES;